### ISSUE TITLE
Add support for SCSS

### ISSUE THREAD

**Issue by rbecheras** [onwidget/storybook-css-modules#1]
The addon works well with vuejs + typescript + CSS

```vue
<template>
  <div :class="$style.myCssClass">
    Hello
  </div>
</template>

<style module lang="css">
.myCssClass {
  color: blue;
}
</style>
```

But it fails with SCSS 

```vue
<style module lang="scss">
.myCssClass {
  color: blue;
}
</style>
```

In this case I get

```
Cannot read properties of undefined (reading 'myCssClass')


```

![Screenshot 2023-08-31 at 16 35 20](https://github.com/onwidget/storybook-css-modules/assets/6469390/65bed62f-c125-4d5b-9b74-89d88f4116ca)

Do you have an idea how to add a support for SCSS ?

**Comment by prototypa** [comment]
Hi @rbecheras 

The addon is not intended to import `scss`. However Storybook already has an addon for various style features, including the one you need. More information here:

https://storybook.js.org/recipes/sass

**Comment by rbecheras** [comment]
Yes this addon supports sass, but not scss modules sadly
